[trade]
env_path = ''
session_id = 123456
account_id = ''

[strategy]
periods = 0.2


[stock]
stock_ids = []
sliding_point = 0.0005
check_order_delay = 10

[assets]
position_avg_mode = true
positions = [] # if you set position_avg_mode = false, set this manually

[ui]
port = 8080 # open http://127.0.0.1:8080/ to view ui, you can custom the server port
record_length = 74000
